// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9VNxr5-Oo6b0DmeDA5C8KQPj_juxrTPE',
    appId: '1:548327728052:web:e286735d49959985dc88e1',
    messagingSenderId: '548327728052',
    projectId: 'tedxvitb',
    authDomain: 'tedxvitb.firebaseapp.com',
    storageBucket: 'tedxvitb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7MJMnbWWH0cKHrpgBV1eqJqJWbxdRBMY',
    appId: '1:548327728052:android:c846c5cb20a25cb9dc88e1',
    messagingSenderId: '548327728052',
    projectId: 'tedxvitb',
    storageBucket: 'tedxvitb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs_iR2qFpYO_4Mv19P3NxfbgIN6HiI-3g',
    appId: '1:548327728052:ios:ff0e96092d73c48adc88e1',
    messagingSenderId: '548327728052',
    projectId: 'tedxvitb',
    storageBucket: 'tedxvitb.appspot.com',
    iosClientId: '548327728052-hdpoqk3hnrl4binduffst6iatnn2t7da.apps.googleusercontent.com',
    iosBundleId: 'com.example.tedxvitb',
  );
}
